---
all:
  children:
    k8s_master:
      hosts:
#        k8s-master1:
#          ansible_host: 10.0.39.130
#        k8s-master2:
#          ansible_host: 10.0.39.131

    k8s_nodes:
      hosts:
#        k8s-node1:
#          ansible_host: 10.0.39.230
        k8s-node2:
          ansible_host: 10.0.39.231
#       k8s-node3:
#         ansible_host: 10.0.39.232
#        k8s-master2:
#          ansible_host: 10.0.39.131
#       k8s-master3:
#         ansible_host: 10.0.39.132

    k8s_cluster:
      children:
        k8s_master: {}
        k8s_nodes: {}
      vars:
        cluster_network: 192.168.5.0/24
        pod_network_cidr: 10.244.0.0/16
        kubernetes_version: 1.30.0
  
  vars:
    ansible_user: ubuntu
    ansible_password: connect
    ansible_become: true
    ansible_become_password: connect
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
